### PR TITLE
fix: orders history fixed

### LINKED ISSUE #183: [Bug]: every order in order history shows the same products
### Expected Behavior

We expect the order history to show product associated to certain orders.

### Actual Behavior

Every order has the same bucket of items (it's actually all the items that come in the api call result).
image

### Possible Solution

Already solved that on Vendo, I am probably gonna copy-paste it.

### Steps to reproduce

_No response_

### What version of Spree integration are you using?

1.2.0

### What version of Node.js are you using?

14.15

### What browser (and version) are you using?

Brave

### What operating system (and version) are you using?

macOS

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by witoldkesek**
## Description
Every order in the orders history was showing the same products. That was a problem related to deserialisation.

## Related Issue
Closes #183 

## How Has This Been Tested?
It was tested in the local environment connected to our test backend.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by rafalcymerys — APPROVED** [review]

**Review by danhaj — APPROVED** [review]

File: packages/api-client/src/api/serializers/cart.ts [hunk 1]
```diff
@@ -60,8 +60,9 @@ const deserializeLineItem = (lineItem: any, attachments: JsonApiDocument[], conf
   };
 };
 
-const filterIncludedLineItems = (included: any[]) => {
-  return included.filter(e => e.type === 'line_item');
+const filterIncludedLineItems = (included: any[], apiCart) => {
+  const cartItemIds = apiCart.relationships.line_items.data.map(l => l.id);
+  return included.filter(e => e.type === 'line_item' && cartItemIds.includes(e.id));
```
Comment (letelete) [inline packages/api-client/src/api/serializers/cart.ts:65]: It would be more efficient to create a Set out of ids and check with .has(e.id)

```
  const cartItemIds = new Set(apiCart.relationships.line_items.data.map(l => l.id));
  return included.filter(e => e.type === 'line_item' && cartItemIds.has(e.id));
```

Comment (witoldkesek) [reply packages/api-client/src/api/serializers/cart.ts:65]: Wow, I didn't know that would be faster. Thanks for pointing it out. Gonna go with it next time as I already merged it.
