### PR TITLE
fix(#236): fix api navigation

### LINKED ISSUE #236: [Bug]: Menu Navigation
### Expected Behavior

_No response_

### Actual Behavior

Left hand vertical sub menu and menu navigation is not clickable , hover mouse showing the parent menu link on all submenu links

### Possible Solution

_No response_

### Steps to reproduce

_No response_

### What version of Spree integration are you using?

4.4

### What version of Node.js are you using?

v14.19.2

### What browser (and version) are you using?

Google chrome DESKTOP Version 101.0.4951.64 (Official Build) (64-bit)

### What operating system (and version) are you using?

ubuntu

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rafalkosla101**
Added a fallback to slug when menu is not provided by api 

## Related Issue

#236
## Motivation and Context

It fixes #236
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: packages/theme/pages/Category.vue [hunk 1]
```diff
@@ -247,7 +247,7 @@ export default {
       if (menu.value.isDisabled) {
         return '/c/' + category.slug;
       }
-      return category.link;
+      return category.link || '/c/' + category.slug;
```
Comment (letelete) [inline packages/theme/pages/Category.vue:250]: It's recommended to use string templates for increased readability.

```suggestion
      return category.link || `/c/${category.slug}`;
```
The above could be simplified to:
```js
return menu.value.isDisabled || !category.link
  ? `/c/${category.slug}`
  : category.link;
```

If you don't prefer a ternary operator, I'd suggest moving the category-based-on-slug route to its own variable to avoid repetition.
so:
```js
const slugBasedRoute = `/c/${category.slug}`;
if (menu.value.isDisabled) {
  return slugBasedRoute;
}
return category.link || slugBasedRoute;
```

**Review by letelete — APPROVED** [review]
