### PR TITLE
fix(#165): removed an option to change shipping details after shipment 

### LINKED ISSUE #165: [Bug]: Modifying shipping details won't invalidate shipping method
### Expected Behavior

A user needs to "go back" to edit details, which invalidates shipping methods.

### Actual Behavior

Shipping methods, once selected, act independently of shipping data (eg. state, country, ...) and aren't invalidated when the data changes.

### Possible Solution

Make checkout process (shipping tab) sequential.

### Steps to reproduce

1. Add product to the shopping  cart
2. Go to the checkout page via the shopping cart
3. Provide shipping details
4. Select shipping method
5. Modify shipping details

### What version of Spree integration are you using?

1.3

### What version of Node.js are you using?

14.19

### What browser (and version) are you using?

Firefox Developers 99.0b3 (64-bit)

### What operating system (and version) are you using?

macOS 12.2.1 (21D62)

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #168: [Bug]: Changing shipping details after shipments are loaded
### Expected Behavior

User cannot change provided shipping details after clicking "select shipping method" since shipping methods are based on provided data which could lead to errors

### Actual Behavior

User can freely change any provided details

### Possible Solution

_No response_

### Steps to reproduce

_No response_

### What version of Spree integration are you using?

1.3.0

### What version of Node.js are you using?

14.18.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rafalkosla101**
Disabled an option to change shipping details when user already called for shipping methods

## Description

Removed possibility to change shipping details after user calls for shipping methods so it won't throw an error in special cases. Added a button that takes user back so she/he can provide details once more and choose appropriate shipping method. Also now while choosing shipping method user can go back to shipping details just by clicking on any of the input  fields or just by clicking saved address(only for logged in users)

## Related Issue

#165
## Motivation and Context

It fixes #165
## How Has This Been Tested?

manually
## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: packages/theme/components/Checkout/VsfShippingProvider.vue [hunk 1]
```diff
@@ -39,6 +50,7 @@ export default {
     const { $spree } = useVSFContext();
     const { setCart } = useCart();
     const { state: shipments, save: saveShipments, load: loadShipments } = useShippingProvider();
+    const getBackToShippingDetails = () => location.reload();
```
Comment (rafalcymerys) [inline packages/theme/components/Checkout/VsfShippingProvider.vue:53]: Hehe, is there a way to do that without reloading the page? I know it's a bit of state management, but would feel much smoother

**Comment by rafalcymerys** [comment]
@rafalkosla101 just a though - what happens to the "Saved addresses" chooser if the user is logged in? We should also block it

**Comment by rafalcymerys** [comment]
> @rafalkosla101 just a though - what happens to the "Saved addresses" chooser if the user is logged in? We should also block it

Currently it will be hidden, right?

**Comment by rafalkosla101** [comment]
@rafalcymerys it will be hidden after user calls for shipping methods

**Comment by rafalcymerys** [comment]
@rafalkosla101 could we disable the saved address picker but still show it? 
This would be consistent with what we have when user enters a custom address + it would reassure them what they chose there

**Comment by letelete** [comment]
> Also for the option to go back to shipping details - we should use a lighter button style, since that's not what's the primary action here. Maybe this one: https://docs.storefrontui.io/?path=/docs/components-atoms-button--secondary#as-link or https://docs.storefrontui.io/?path=/docs/components-atoms-button--disabled#light would work?

> Also for the option to go back to shipping details - we should use a lighter button style, since that's not what's the primary action here. Maybe this one: https://docs.storefrontui.io/?path=/docs/components-atoms-button--secondary#as-link or https://docs.storefrontui.io/?path=/docs/components-atoms-button--disabled#light would work?

Agree. We should create the [visual distinction](https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150) between a primary and secondary action to improve the UX and be consistent with the design. We're already using the secondary button for "GO BACK" action (secondary action) in the Billing step, so I would strongly recommend going with this one.

**Comment by letelete** [comment]
Shouldn't we maintain consistency across checkout steps and align Shipping buttons in the same way as Billing buttons are aligned (in a row instead of a column)?

**Shipping**
image

**Billing**
image

File: packages/theme/pages/Checkout/Shipping.vue [hunk 2]
```diff
@@ -7,7 +7,7 @@
       class="sf-heading--left sf-heading--no-underline title"
     />
     <AddressPicker
-      v-if="isAuthenticated && savedAddresses"
+      v-if="isAuthenticated && savedAddresses && !isFormSubmitted"
```
Comment (letelete) [inline packages/theme/pages/Checkout/Shipping.vue:10]: The v-if is getting complicated; could we transform it into isAdressPickerVisible `computable` to improve readability?

File: packages/theme/pages/Checkout/Shipping.vue [hunk 3]
```diff
@@ -225,6 +235,7 @@
       <VsfShippingProvider
         v-if="isFormSubmitted"
         @submit="router.push(localePath({ name: 'billing' }))"
+        @back="() => isFormSubmitted = !isFormSubmitted"
```
Comment (letelete) [inline packages/theme/pages/Checkout/Shipping.vue:238]: Just a thought - would it make sense to create a handler in the setup() to toggle the form editability here? To separate the concerns. Additionally, renaming isFormSubmitted to isFormEditable (it would require negating already used isFormSubmitted - so !isFormSubmitted -> !!isFormEditable -> isFormEditable; isFormSubmitted -> !isFormEditable).

Comment (rafalkosla101) [reply packages/theme/pages/Checkout/Shipping.vue:238]: For now I will let it be as it is since i think that submission of the form is tightly tied with the process

File: packages/theme/pages/Checkout/Shipping.vue [hunk 4]
```diff
@@ -22,6 +26,8 @@
           slim
         >
           <SfInput
+            v-on:click="getBackToShippingDetails()"
+            v-bind:class="{'disbale-input': isFormSubmitted}"
```
Comment (rafalcymerys) [inline packages/theme/pages/Checkout/Shipping.vue:30]: This seems like a typo

```suggestion
            :class="{'disable-input': isFormSubmitted}"
```

File: packages/theme/pages/Checkout/Shipping.vue [hunk 5]
```diff
@@ -37,6 +43,8 @@
           slim
         >
           <SfInput
+            v-on:click="getBackToShippingDetails()"
+            v-bind:class="{'disable-input': isFormSubmitted}"
```
Comment (rafalcymerys) [inline packages/theme/pages/Checkout/Shipping.vue:47]: Same as above, let's skip `v-bind`s

**Review by rafalcymerys — APPROVED** [review]
