### PR TITLE
fix(#185): checkout and order products now link to themselves

### LINKED ISSUE #185: [Bug]: products don't redirect to product pages in order history
### Expected Behavior

When you click on a product in the order history it should redirect you to the product page.

### Actual Behavior

You aren't redirected to the product page. Instead you are redirected to the "Page not found" page. It is caused by missing item's id in the link to the product.
Screenshot 2022-03-25 at 14 59 11
Screenshot 2022-03-25 at 15 18 25

### Possible Solution

_No response_

### Steps to reproduce

_No response_

### What version of Spree integration are you using?

1.2.0

### What version of Node.js are you using?

14.15

### What browser (and version) are you using?

Brave

### What operating system (and version) are you using?

macOS

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by witoldkesek**
## Description
Products in the Order History didn't redirect to their pages, instead they did redirect to blank "not found" pages. These changes introduce proper id and slug passing, so there can be proper links created. Also did the same thing for products in the cart. 

## Related Issue
Closes #185 
## Motivation and Context
Changes for the cart and order history give more natural and intuitive feeling while using the app.

## How Has This Been Tested?
It was tested in the local environment connected to our Heroku backend.

## Screenshots (if appropriate):
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by letelete — APPROVED** [review]

File: packages/api-client/src/api/serializers/cart.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ const deserializeLineItem = (lineItem: any, attachments: JsonApiDocument[], conf
     _description: '',
     _categoriesRef: [],
     name: lineItem.attributes.name,
-    sku: '',
+    sku: lineItem.attributes.slug,
```
Comment (rafalcymerys) [inline packages/api-client/src/api/serializers/cart.ts:50]: Slug is not SKU, so let's not assign it.
Maybe we should assign slug to another attribute (`slug` or `productSlug`) and just extract that attribute when linking to product page?

Comment (witoldkesek) [reply packages/api-client/src/api/serializers/cart.ts]: I agree, took care of that. Should be good now

File: packages/composables/src/getters/cartGetters.ts [hunk 2]
```diff
@@ -3,6 +3,8 @@ import { Cart, LineItem } from '@vue-storefront/spree-api/src/types';
 
 export const getCartItems = (cart: Cart): LineItem[] => cart?.lineItems || [];
 
+export const getCartItemId = (lineItem: LineItem): number => lineItem?._variantId;
```
Comment (rafalcymerys) [inline packages/composables/src/getters/cartGetters.ts:6]: The name `getCartItemId` may be confusing, since line items have their own id as well. Maybe `getCartItemVariantId`, just to be explicit?

Comment (witoldkesek) [reply packages/composables/src/getters/cartGetters.ts]: Fixed it.

**Review by rafalcymerys — APPROVED** [review]
